FROM trufflesuite/ganache-cli:latest
EXPOSE 8545
ENTRYPOINT ["node", "/app/ganache-core.docker.cli.js", "--host", "0.0.0.0", "--accounts", "4", "--deterministic", "-v", "--mnemonic", "unfold bachelor enact fiber later donate uncover once torch figure engine keep"]
